const prompts = {
    "基本情報": {
      "品質": [
        ["傑作", "masterpiece"],
        ["最高傑作", "best quality"],
        ["高画質", "high quality"],
        ["高解像度", "high resolution"],
        ["美しい", "beautiful"],
        ["綺麗", "gorgeous"],
        ["詳細", "detailed"],
        ["細部まで描き込まれた", "intricate details"],
        ["リアル", "realistic"],
        ["現実的", "lifelike"],
        ["鮮明", "sharp focus"],
        ["クリア", "clear"],
        ["完璧な構成", "perfect composition"],
        ["滑らかな質感", "smooth texture"],
        ["シャープなエッジ", "sharp edges"],
        ["ソフトな光", "soft lighting"],
        ["自然な光", "natural lighting"],
        ["鮮やかな色", "vibrant colors"],
        ["正確な色", "accurate colors"],
        ["ハイコントラスト", "high contrast"],
        ["ローコントラスト", "low contrast"],
        ["プロフェッショナルな仕上がり", "professional quality"],
        ["芸術的な", "artistic"],
        ["映画のような", "cinematic"],
        ["スタジオ品質", "studio quality"],
        ["フォトリアリスティック", "photorealistic"],
        ["8k","8k"],
        ["4k","4k"],
        ["奥行きのある表現", "depth of field"],
        ["完璧な陰影", "perfect shadows and highlights"],
        ["美しい反射", "beautiful reflections"],
        ["複雑なディテール","complex details"],
        ["優れたテクスチャ", "excellent texture"],
        ["高精細","high definition"]
      ],
      "画風": [
        ["写実的", "photorealistic"],
        ["油絵風", "oil painting style"],
        ["水彩画風", "watercolor style"],
        ["イラスト風", "illustration style"],
        ["アニメ風", "anime style"],
        ["漫画風", "manga style"],
        ["3Dレンダリング", "3D rendering"],
        ["ピクセルアート", "pixel art"],
        ["印象派", "impressionism"],
        ["ゴッホ風", "van gogh style"],
        ["クリムト風", "klimt style"],
        ["アールヌーボー", "art nouveau"],
        ["シュルレアリスム", "surrealism"]
      ],
      "シーン/背景": {
        "場所": {
          "室内": [
            ["屋内", "indoors"],
            ["リビング", "living room"],
            ["キッチン", "kitchen"],
            ["オフィス", "office"],
            ["カフェ", "cafe"],
            ["学校", "school"],
            ["図書館", "library"],
            ["ショッピングモール", "shopping mall"],
            ["映画館", "movie theater"],
            ["ホテル", "hotel"],
            ["レストラン", "restaurant"],
            ["バー", "bar"],
            ["クラブ", "club"],
            ["研究室", "laboratory"],
            ["病院", "hospital"],
            ["工場", "factory"],
            ["寺院", "temple"],
            ["教会", "church"],
            ["監獄", "prison"],
            ["博物館", "museum"],
            ["美術館", "art gallery"]
          ],
          "屋外": [
            ["屋外", "outdoors"],
            ["公園", "park"],
            ["森林", "forest"],
            ["海", "sea"],
            ["街中", "city"],
            ["路地裏", "back alley"],
            ["広場", "plaza"],
            ["市場", "market"],
            ["駅", "train station"],
            ["空港", "airport"],
            ["高層ビル", "skyscraper"],
            ["橋", "bridge"],
            ["トンネル", "tunnel"],
            ["遊園地", "amusement park"],
            ["スタジアム", "stadium"],
            ["山", "mountain"],
            ["砂漠", "desert"],
            ["川", "river"],
            ["湖", "lake"],
            ["滝", "waterfall"],
            ["洞窟", "cave"],
            ["草原", "grassland"],
            ["丘", "hill"],
            ["島", "island"],
            ["海岸", "coast"],
            ["熱帯雨林", "rainforest"],
            ["サバンナ", "savanna"],
            ["湿地", "wetland"],
            ["雪山", "snowy mountain"],
            ["火山", "volcano"],
            ["峡谷", "canyon"],
            ["農場", "farm"],
            ["墓地", "cemetery"],
            ["潜水艦", "submarine"],
            ["宇宙ステーション", "space station"]
          ],
          "ファンタジー": [
            ["ファンタジー世界", "fantasy world"],
            ["古代遺跡","ancient ruins"],
            ["魔法の森","enchanted forest"],
            ["クリスタル洞窟","crystal cave"],
            ["浮遊島","floating islands"],
            ["城","castle"],
            ["ダンジョン","dungeon"]
          ]
        },
        "時間帯": [
          ["朝", "morning"],
          ["昼", "daytime"],
          ["夕方", "evening"],
          ["夜", "night"],
          ["深夜", "late night"]
        ],
        "天気": [
          ["晴れ", "sunny"],
          ["曇り", "cloudy"],
          ["雨", "rainy"],
          ["雪", "snowy"],
          ["霧", "foggy"],
          ["雷雨", "thunderstorm"]
        ]
      },
      "時代設定": [
        ["古代", "ancient"],
        ["中世", "medieval"],
        ["近世", "early modern"],
        ["現代", "modern"],
        ["未来", "futuristic"],
        ["ファンタジー", "fantasy"]
      ],
       "光源": [
        ["自然光", "natural light"],
        ["蛍光灯", "fluorescent light"],
        ["スポットライト", "spotlight"],
        ["キャンドル", "candle light"],
        ["炎", "fire light"],
        ["月光", "moonlight"]
      ],
      "画角": [
        ["全身", "full shot"],
        ["上半身", "medium shot"],
        ["バストアップ", "bust shot"],
        ["顔のアップ", "close-up shot"],
        ["クローズアップ", "extreme close-up shot"]
      ],
       "構図": {
        "基本的な構図":[
          ["中心", "centered"],
          ["三分割", "rule of thirds"],
          ["対角線", "diagonal composition"]
        ],
        "透視図法":[
          ["一点透視", "one point perspective"],
          ["二点透視", "two point perspective"]
         ],
        "遠近感":[
          ["遠近感のある", "depth of field"],
          ["ぼかし", "bokeh"]
        ],
         "装飾的な構図":[
          ["額縁構図", "frame in frame"],
          ["トンネル構図", "tunnel composition"]
        ],
        "視点":[
          ["鳥瞰図", "bird's eye view"],
          ["ローアングル", "low angle"]
        ]
      }
    },
    "人物概要": {
      "性別": [
        ["男性", "man"],
        ["女性", "woman"],
        ["少年", "boy"],
        ["少女", "girl"]
      ],
      "年齢": [
        ["子供", "child"],
        ["10代", "teenager"],
        ["20代", "young adult"],
        ["30代", "adult"],
        ["40代", "middle-aged"],
        ["50代以上", "elderly"]
      ],
      "人種": [
        ["アジア系", "asian"],
        ["白人系", "caucasian"],
        ["アフリカ系", "african"],
        ["ラテン系", "latino"],
        ["インド系", "indian"],
        ["中東系", "middle eastern"],
        ["日本人", "japanese"],
        ["中国人", "chinese"],
        ["韓国人", "korean"],
        ["イギリス人","british"],
        ["フランス人","french"],
        ["ドイツ人","german"],
        ["イタリア人","italian"],
        ["スペイン人","spanish"],
        ["ロシア人","russian"],
        ["ブラジル人","brazilian"],
        ["カナダ人","canadian"],
        ["ギリシャ人","greek"],
        ["エジプト人","egyptian"],
        ["ケニア人","kenyan"]
      ],
      "属性": {
        "職業":[
          ["ビジネスマン", "businessman"],
          ["ビジネスウーマン", "businesswoman"],
          ["男子学生","school boy"],
          ["女子学生","school girl"],
          ["教師", "teacher"],
          ["医者", "doctor"],
          ["看護師", "nurse"],
          ["警察官", "police officer"],
          ["消防士", "firefighter"],
          ["シェフ", "chef"],
          ["アイドル", "idol"],
          ["アーティスト", "artist"],
          ["エンジニア", "engineer"],
          ["メイド", "maid"],
          ["執事", "butler"],
          ["農家", "farmer"],
          ["漁師", "fisherman"],
          ["職人", "craftsman"]
        ],
        "ファンタジー":[
          ["冒険家", "adventurer"],
          ["騎士", "knight"],
          ["魔法使い", "wizard"],
          ["魔女", "witch"],
          ["エルフ", "elf"],
          ["ドワーフ", "dwarf"],
          ["獣人", "furry"]
        ],
        "人造/異形":[
          ["アンドロイド", "android"],
          ["サイボーグ", "cyborg"],
          ["天使", "angel"],
          ["悪魔", "demon"],
          ["神", "god"],
          ["妖精", "fairy"],
          ["幽霊", "ghost"],
          ["ゾンビ","zombie"],
          ["吸血鬼", "vampire"],
          ["宇宙人","alien"],
          ["超能力者","psychic"]
        ]
      },
      "雰囲気/ムード": [
        ["落ち着いた", "calm"],
        ["神秘的", "mysterious"],
        ["壮大な","epic"],
        ["幽玄な","ethereal"],
        ["夢のような","dreamlike"],
        ["気まぐれな","whimsical"],
        ["おとぎ話のような","fairytale"],
        ["シュールな","surreal"],
        ["ロマンチック", "romantic"],
        ["魅惑的な","alluring"],
        ["官能的な", "sensual"],
        ["色っぽい","come-hither"],
        ["魅惑的な", "seductive"],
        ["挑発的な", "provocative"],
        ["活気のある", "energetic"],
        ["楽しい", "happy"],
        ["悲しい", "sad"],
        ["怖い", "scary"],
        ["豊満な", "voluptuous"]
      ]
    },
    "外見的特徴": {
      "外見": [
        ["角","horns"],
        ["翼","wings"],
        ["尻尾","tail"],
        ["鱗","scales"],
        ["獣の耳","animal ears"],
        ["尖った耳","pointed ears"],
        ["エルフの耳","elf ears"]
      ],
      "体型": [
        ["細身だが胸筋がある", "lean but has chest muscles"],
        ["筋肉隆々", "heavily muscled"],
        ["引き締まった筋肉", "toned muscles"],
        ["細マッチョ", "lean muscled"],
        ["がっしりとした", "stocky build"],
        ["アスリート体型", "athletic build"],
        ["スレンダー", "slender"],
        ["小柄","petite"],
        ["大柄","large build"],
        ["華奢","delicate build"],
        ["曲線美", "curvy figure"],
        ["くびれのある体型", "hourglass figure"],
        ["ぽっちゃり", "plump"],
        ["グラマー", "glamorous"],
        ["豊満", "voluptuous"],
        ["足が長い","long legs"],
        ["巨体","giant build"],
        ["妖精のような体型","fairy-like figure"],
        ["ウエストが細い", "narrow waist"]
      ],
      "肌の色": [
        ["薄い色の肌", "pale skin"],
        ["明るい色の肌", "light skin"],
        ["アイボリー色の肌", "ivory skin"],
        ["ベージュ色の肌", "beige skin"],
        ["ピンクがかった肌", "pinkish skin"],
        ["黄色がかった肌", "yellowish skin"],
        ["赤みがかった色の肌", "reddish skin"],
        ["オリーブ色の肌", "olive skin"],
        ["小麦色の肌", "tan skin"],
        ["キャラメル色の肌", "caramel skin"],
        ["濃い色の肌","dark skin"],
        ["深い色の肌","deep skin"],
        ["青みがかった色の肌", "bluish skin"],
        ["白人系の肌", "caucasian skin"],
        ["アジア系の肌", "asian skin"],
        ["アフリカ系の肌", "african skin"],
        ["ラテン系の肌", "latino skin"],
        ["先住民の肌","indigenous skin"]
      ],
      "顔の特徴": {
        "目": [
          ["黒い目", "black eyes"],
          ["茶色い目", "brown eyes"],
          ["青い目", "blue eyes"],
          ["緑の目", "green eyes"],
          ["ヘーゼルアイ", "hazel eyes"],
          ["琥珀色の目", "amber eyes"],
          ["灰色の目", "gray eyes"],
          ["紫色の目", "purple eyes"],
          ["ターコイズアイ", "turquoise eyes"],
          ["オッドアイ", "heterochromia eyes"],
          ["大きい目", "large eyes"],
          ["小さい目", "small eyes"],
          ["つり目", "almond eyes"],
          ["たれ目", "droopy eyes"],
          ["奥二重", "hooded eyes"],
          ["色っぽい目つき","seductive eyes"]
        ],
        "鼻": [
          ["高い鼻", "high nose"],
          ["低い鼻", "low nose"],
          ["小さい鼻", "small nose"],
          ["大きい鼻", "large nose"],
          ["丸い鼻", "round nose"],
          ["尖った鼻", "pointed nose"]
        ],
        "口": [
          ["大きい口", "large mouth"],
          ["小さい口", "small mouth"],
          ["厚い唇", "full lips"],
          ["薄い唇", "thin lips"],
          ["少し開いた口元", "slightly parted lips"],
          ["への字口", "down turned mouth"]
        ],
         "輪郭": [
          ["ふっくらとした頬", "chubby cheeks"],
          ["顎がシャープ", "sharp jawline"],
          ["女性的な顔つき", "feminine face"],
          ["男性的な顔つき", "masculine face"]
         ]
      },
       "ヘアスタイル": {
        "長さ": [
          ["ショート", "short hair"],
          ["ミディアム", "medium hair"],
          ["ロング", "long hair"]
        ],
        "質感": [
          ["サラサラヘア", "silky hair"],
          ["ツヤツヤヘア", "shiny hair"],
          ["パサパサヘア", "dry hair"],
          ["ふわふわヘア", "fluffy hair"],
          ["ボリュームのある髪", "voluminous hair"],
          ["ボリュームのない髪", "flat hair"],
          ["乱れた髪", "messy hair"],
          ["整った髪", "neat hair"],
          ["風になびく髪", "hair blowing in the wind"],
          ["濡れた髪", "wet hair"],
          ["汗ばんだ髪", "sweaty hair"],
          ["オイルを塗ったような髪", "oiled hair"],
          ["寝癖のついた髪", "bed hair"]
        ],
        "色": [
          ["黒い髪", "black hair"],
          ["茶色い髪", "brown hair"],
          ["ブロンドヘア", "blonde hair"],
          ["赤い髪", "red hair"],
          ["アッシュヘア", "ash hair"],
          ["グレーヘア", "gray hair"],
          ["白い髪", "white hair"]
        ],
         "スタイル": [
          ["ストレートヘア", "straight hair"],
          ["ウェーブヘア", "wavy hair"],
          ["カーリーヘア", "curly hair"],
          ["かきあげヘア","swept-back hair"],
          ["ポニーテール", "ponytail"],
          ["お団子", "bun hair"],
          ["三つ編み", "braided hair"],
          ["アフロヘア", "afro hair"],
          ["ボブヘア", "bob hair"],
          ["刈り上げ", "shaved hair"]
        ]
      },
      "胸": [
        ["細身だが胸筋がある", "lean but has chest muscles"],
        ["胸筋が発達した","developed chest muscles"],
        ["ハリのある胸", "firm bust"],
        ["ボリュームのある胸", "voluminous bust"],
        ["豊満な胸", "ample bust"],
        ["谷間が見える胸", "cleavage bust"],
        ["やや大きい胸", "slightly large bust"],
        ["非常に大きい胸", "very large bust"],
        ["控えめな胸", "modest bust"],
        ["やや小さい胸", "slightly small bust"],
        ["非常に小さい胸", "very small bust"],
        ["平坦な胸", "flat chest"]
      ],
      "メガネ/サングラス": [
        ["メガネ", "glasses"],
        ["サングラス", "sunglasses"],
        ["スクエア型", "square glasses"],
        ["ラウンド型", "round glasses"],
        ["キャットアイ型", "cat eye glasses"]
      ],
      "メイク": [
        ["ナチュラルメイク", "natural makeup"],
        ["濃いメイク", "heavy makeup"],
        ["赤リップ", "red lipstick"],
        ["スモーキーアイ", "smoky eyes"]
      ],
       "タトゥー/傷跡": [
        ["なし", "no tattoos, no scars"],
        ["タトゥー", "tattoo"],
        ["花", "flower tattoo"],
        ["動物", "animal tattoo"],
        ["幾何学模様", "geometric tattoo"],
        ["文字", "letter tattoo"],
        ["傷跡", "scar"],
        ["顔の傷", "face scar"],
        ["体の傷", "body scar"],
        ["切り傷", "cut scar"],
        ["火傷の跡", "burn scar"]
      ]
    },
    "姿勢と動作": {
      "ポーズ": {
        "基本的な立ちポーズ": [
          ["直立不動", "standing straight"],
          ["リラックスした立ち姿", "relaxed standing pose"],
          ["片足重心の立ち姿", "standing with weight on one leg"],
          ["腰に手を当てて立つ", "standing with hands on hips"],
          ["腕を組んで立つ", "standing with arms crossed"],
          ["壁に寄りかかって立つ", "standing leaning against the wall"],
          ["足を少し開いて立つ", "standing with feet slightly apart"],
          ["足を閉じて立つ", "standing with feet together"]
        ],
        "基本的な座りポーズ": [
          ["椅子に座る", "sitting on a chair"],
          ["床に座る", "sitting on the floor"],
          ["足を組んで座る", "sitting with legs crossed"],
          ["足を伸ばして座る", "sitting with legs extended"],
          ["膝を抱えて座る", "sitting with knees hugged"],
          ["あぐらをかいて座る", "sitting cross-legged"],
          ["正座する", "sitting in seiza"],
          ["ソファに座る", "sitting on a sofa"],
          ["階段に座る", "sitting on stairs"],
          ["縁に腰掛ける", "sitting on an edge"]
        ],
        "動きのあるポーズ": [
          ["歩く", "walking"],
          ["走る", "running"],
          ["振り返る", "looking back"],
          ["ジャンプする", "jumping"],
          ["手を振る", "waving hand"],
          ["何かを指さす", "pointing at something"],
          ["手を伸ばす", "reaching out"],
          ["腕を回す", "swinging arms"],
          ["しゃがむ", "squatting"],
          ["かがむ", "bending over"],
          ["ストレッチをする", "stretching"],
          ["飛び跳ねる", "skipping"],
          ["回転する", "spinning"],
          ["踊る", "dancing"]
        ],
        "感情や状態を表すポーズ": [
          ["考えるポーズ", "thinking pose"],
          ["驚いたポーズ", "surprised pose"],
          ["怒っているポーズ", "angry pose"],
          ["悲しんでいるポーズ", "sad pose"],
          ["喜んでいるポーズ", "happy pose"],
          ["疲れたポーズ", "tired pose"],
          ["リラックスしているポーズ", "relaxed pose"],
          ["悩んでいるポーズ", "worried pose"],
          ["恥ずかしがっているポーズ", "embarrassed pose"],
          ["挑発的なポーズ", "provocative pose"],
          ["自信に満ちたポーズ", "confident pose"],
          ["警戒しているポーズ", "cautious pose"],
          ["落ち着いているポーズ", "calm pose"]
        ],
        "その他のポーズ": [
          ["片手を上げる", "raising one hand"],
          ["両手を上げる", "raising both hands"],
          ["頭を抱える", "holding head"],
          ["胸に手を当てる", "hand on chest"],
          ["頬に手を当てる", "hand on cheek"],
          ["祈るポーズ", "praying pose"],
          ["敬礼する", "saluting"],
          ["腰をかがめる", "bending at the waist"],
          ["後ろを向く", "facing away"],
          ["横を向く", "facing sideways"],
          ["膝をつく", "kneeling"],
          ["うつ伏せになる", "lying on stomach"],
          ["仰向けになる", "lying on back"],
          ["壁にもたれかかる", "leaning against a wall"],
          ["座って本を読む", "sitting and reading a book"],
          ["手を繋ぐ", "holding hands"],
          ["ハグをする", "hugging"],
          ["キスをする", "kissing"],
          ["戦うポーズ", "fighting pose"],
          ["武器を構える", "wielding a weapon"],
          ["楽器を演奏する", "playing an instrument"],
          ["物を持ち上げる", "lifting an object"],
          ["物を運ぶ", "carrying an object"],
          ["何かを指し示す", "pointing at something"]
        ]
      },
      "表情": [
        ["真顔", "neutral face"],
        ["笑顔", "smiling"],
        ["妖艶な微笑み", "seductive smile"],
        ["アンニュイな表情", "ennui expression"],
        ["喜び", "joyful"],
        ["悲しみ", "sad"],
        ["怒り", "angry"],
        ["驚き", "surprised"],
        ["不安", "anxious"],
        ["悩み", "worried"],
        ["挑発的な視線", "provocative gaze"]
      ],
       "姿勢": [
        ["直立", "upright"],
        ["猫背", "slouching"],
        ["リラックス", "relaxed"],
        ["前かがみ", "leaning forward"],
        ["反り返る", "leaning backward"]
      ],
      "視線": {
        "基本的な視線": [
          ["正面を見る", "looking at the camera"],
          ["左を見る", "looking to the left"],
          ["右を見る", "looking to the right"],
          ["上を見る", "looking up"],
          ["下を見る", "looking down"],
          ["斜め上を見る", "looking up to the side"],
          ["斜め下を見る", "looking down to the side"],
          ["遠くを見る", "looking into the distance"],
          ["近くを見る", "looking at something nearby"],
          ["何かを見つめる", "staring at something"]
        ],
        "感情を伴う視線": [
          ["優しい眼差し", "gentle gaze"],
          ["鋭い眼差し", "sharp gaze"],
          ["悲しげな眼差し", "sad gaze"],
          ["怒りの眼差し", "angry gaze"],
          ["喜びに満ちた眼差し", "joyful gaze"],
          ["驚いた眼差し", "surprised gaze"],
          ["不安そうな眼差し", "anxious gaze"],
          ["挑発的な眼差し", "provocative gaze"],
          ["好奇心に満ちた眼差し", "curious gaze"],
          ["疑いの眼差し", "suspicious gaze"],
          ["冷たい眼差し", "cold gaze"],
          ["魅惑的な眼差し", "alluring gaze"],
          ["見下す眼差し", "looking down on"],
          ["見上げる眼差し", "looking up at"],
          ["無関心な眼差し", "indifferent gaze"],
          ["恥ずかしそうな眼差し", "bashful gaze"],
          ["思慮深い眼差し", "thoughtful gaze"],
          ["瞑想的な眼差し", "meditative gaze"],
          ["夢見るような眼差し", "dreamy gaze"]
        ],
        "特定の対象物を見る視線": [
          ["カメラを直視する", "looking directly at the camera"],
          ["観客を見る", "looking at the audience"],
          ["誰かを見る", "looking at someone"],
          ["何かを探すように見る", "looking around"],
          ["画面を見つめる", "looking at the screen"],
          ["本を見つめる", "looking at the book"],
          ["空を見上げる", "looking up at the sky"],
          ["地面を見る", "looking down at the ground"],
          ["鏡を見る", "looking at a mirror"]
        ],
        "視線の状態": [
          ["焦点が合っていない視線", "unfocused gaze"],
          ["潤んだ瞳", "watery eyes"],
          ["焦点の合った視線", "focused gaze"],
          ["目を細めて見る", "squinting eyes"],
          ["見開いた目", "wide-eyed"],
          ["目をそらす", "averting eyes"],
          ["伏し目がち", "downcast eyes"],
          ["視線を合わせない", "avoiding eye contact"],
          ["視線を交わす", "making eye contact"],
          ["睨みつける", "glaring"]
        ]
      }
    },
    "服装と装飾品": {
      "服装": {
        "全体":{
          "基本的な服装":[
            ["カジュアル", "casual clothing"],
            ["スポーティ", "sporty clothing"],
            ["ストリート","street fashion"],
            ["フォーマル", "formal clothing"]
          ],
          "服の柄": [
            ["無地の服", "plain clothing"],
            ["ストライプ柄の服", "striped clothing"],
            ["ドット柄の服", "dotted clothing"],
            ["チェック柄の服", "checkered clothing"],
            ["花柄の服", "floral clothing"],
            ["幾何学模様の服", "geometric pattern clothing"],
            ["アニマル柄の服", "animal print clothing"],
            ["ペイズリー柄の服", "paisley pattern clothing"],
            ["水玉模様の服", "polka dot clothing"],
            ["迷彩柄の服", "camouflage pattern clothing"],
            ["グラデーションの服", "gradient clothing"],
            ["抽象的な模様の服", "abstract pattern clothing"],
            ["民族衣装の柄", "ethnic pattern clothing"]
          ],
          "特定のスタイル":[
            ["ゴシック", "gothic clothing"],
            ["和風", "japanese clothing"],
            ["ファンタジー", "fantasy clothing"],
            ["パンク", "punk clothing"],
            ["サイバーパンク", "cyberpunk clothing"],
            ["ロリータ", "lolita fashion"],
            ["ボヘミアン","bohemian fashion"],
            ["ウェディング","wedding dress"]
          ],
          "制服":[
            ["制服", "uniform"],
            ["学生服","school uniform"],
            ["医者の白衣", "doctor's coat"],
            ["看護師の制服","nurse uniform"],
            ["警察官の制服", "police uniform"],
            ["消防士の制服", "firefighter uniform"],
            ["ミリタリー", "military clothing"],
            ["パイロットの制服", "pilot uniform"],
            ["シェフの制服","chef uniform"]
          ],
          "露出度が高い服装":[
            ["露出度の高い服", "revealing clothes"],
            ["ランジェリー風", "lingerie-like clothing"],
            ["セクシー", "sexy clothing"],
            ["体にフィットした服","body-hugging clothes"],
            ["キャミソール", "camisole"],
            ["ベビードール", "babydoll"],
            ["ボディスーツ","bodysuit"],
            ["コルセット", "corset"],
            ["シースルー", "see-through clothing"]
          ],
          "水着":[
            ["水着", "swimsuit"],
            ["ビキニ", "bikini"],
            ["ハイレグビキニ", "high-leg bikini"],
            ["マイクロビキニ", "micro bikini"],
            ["ストリングビキニ", "string bikini"],
            ["バンドゥビキニ", "bandeau bikini"],
            ["トライアングルビキニ", "triangle bikini"],
            ["ワンピース水着", "one-piece swimsuit"],
            ["モノキニ", "monokini"],
            ["スクール水着", "school swimsuit"],
            ["ハイネック水着", "high-neck swimsuit"],
            ["カットアウト水着", "cutout swimsuit"],
            ["バックレス水着", "backless swimsuit"],
            ["タンキニ", "tankini"],
            ["ラッシュガード", "rash guard"],
            ["競泳水着", "competition swimsuit"],
            ["フィットネス水着", "fitness swimsuit"],
            ["ビキニアーマー", "bikini armor"],
            ["露出度の高い水着", "revealing swimsuit"],
            ["露出度の低い水着", "modest swimsuit"]
          ],
          "服の様子": [
            ["少しはだけた", "slightly open clothing"],
            ["胸元がはだけた", "chest area is slightly open"],
            ["肩が露出した", "shoulder is exposed"],
            ["服がずり落ちそう", "clothing is slipping off"],
            ["服が大きく開いている", "clothing is widely open"],
            ["服が乱れている", "disheveled clothing"],
            ["服がはだけて肌が見える", "clothing is open, revealing skin"],
            ["ボタンが外れたシャツ", "unbuttoned shirt"],
            ["ジッパーが開いたジャケット", "unzipped jacket"],
            ["肩から服が落ちかけている", "clothing slipping off the shoulder"],
            ["スカートが少しずり下がった", "skirt slightly slipped down"],
            ["着崩したシャツ", "loosely worn shirt"],
            ["服の襟元が開いている", "open neckline"],
            ["胸元が開いた服", "open-chested clothing"],
            ["服が大きくはだけて胸が見える", "clothing is largely open, revealing the bust"],
            ["風で服がめくれ上がった", "clothing is blown up by the wind"],
            ["動きで服が乱れた", "clothing is disheveled by movement"],
            ["激しい動きで服がはだけた", "clothing is opened by intense movement"],
            ["アクティブなポーズで服がはだけた", "clothing is opened by an active pose"],
            ["ダンスで服が乱れてはだけた", "clothing is disheveled and opened by dance"],
            ["喧嘩で服がはだけた", "clothing is opened in a fight"],
            ["衣服が一部破れている", "partially torn clothing"],
            ["シャツのボタンがいくつか外れている", "some shirt buttons are undone"]
          ]
        },
        "トップス": [
          ["トップスなし", "no top"],
          ["Tシャツ", "t-shirt"],
          ["シャツ", "shirt"],
          ["ポロシャツ", "polo shirt"],
          ["ブラウス", "blouse"],
          ["タンクトップ", "tank top"],
          ["キャミソール", "camisole"],
          ["チューブトップ", "tube top"],
          ["ホルターネック", "halter neck top"],
          ["オフショルダー", "off-shoulder top"],
          ["クロップドトップ","cropped top"],
          ["ビスチェ", "bustier"],
          ["ボディスーツ", "bodysuit"],
          ["タートルネック", "turtleneck"],
          ["ニット", "knit sweater"],
          ["パーカー", "hoodie"],
          ["カーディガン", "cardigan"],
          ["ブレザー", "blazer"],
          ["スウェット", "sweatshirt"],
          ["ジャケット", "jacket"],
          ["コート", "coat"],
          ["ベスト", "vest"],
          ["ボレロ", "bolero"],
          ["チュニック", "tunic"],
          ["レーストップス", "lace top"],
          ["メッシュトップス","mesh top"],
          ["フリルブラウス","frilled blouse"],
          ["パフスリーブブラウス","puff sleeve blouse"],
          ["シースルー", "see-through top"],
          ["キャミソールワンピース","camisole dress"],
          ["オーバーサイズシャツ","oversized shirt"],
          ["ノースリーブシャツ","sleeveless shirt"],
          ["ロングスリーブシャツ","long sleeve shirt"],
          ["ハーフスリーブシャツ","half sleeve shirt"],
          ["ボタンダウンシャツ","button-down shirt"],
          ["ドレス", "dress"],
          ["着物", "kimono"],
          ["鎧", "armor"],
          ["ローブ", "robe"]
        ],
        "ボトムス": [
          ["ボトムスなし", "no bottoms"],
          ["ジーンズ", "jeans"],
          ["パンツ", "pants"],
          ["スキニーパンツ","skinny pants"],
          ["ワイドパンツ", "wide pants"],
          ["ショートパンツ", "shorts"],
          ["ホットパンツ","hot pants"],
          ["ショート丈のパンツ","short shorts"],
          ["スカート", "skirt"],
          ["ミニスカート", "mini skirt"],
          ["フレアスカート","flare skirt"],
          ["プリーツスカート","pleated skirt"],
          ["タイトスカート","tight skirt"],
          ["ロングスカート","long skirt"],
          ["ミディスカート","midi skirt"],
          ["Aラインスカート","A-line skirt"],
          ["デニムスカート","denim skirt"],
          ["レギンス", "leggings"],
          ["カーゴパンツ", "cargo pants"],
          ["チノパンツ", "chino pants"],
          ["スラックス", "slacks"],
          ["ガウチョパンツ", "gaucho pants"],
          ["ジョガーパンツ", "jogger pants"],
          ["サルエルパンツ", "sarouel pants"],
          ["レザーパンツ", "leather pants"],
          ["ベルボトム", "bell bottoms"],
          ["バギーパンツ", "baggy pants"],
          ["キュロット","culottes"],
          ["サロペット","overall"],
          ["ジャージ","jersey pants"],
          ["スウェットパンツ","sweatpants"],
          ["袴", "hakama"]
        ],
        "靴": [
          ["スニーカー", "sneakers"],
          ["革靴", "leather shoes"],
          ["ブーツ", "boots"],
          ["サンダル", "sandals"],
          ["ハイヒール", "high heels"]
        ],
        "下着": {
          "基本的な下着":[
            ["下着なし", "no panties"],
            ["ブラジャー", "bra"],
            ["ショーツ", "panties"]
          ],
          "ランジェリー":[
            ["ランジェリー", "lingerie"],
            ["キャミソール", "camisole"],
            ["スリップ", "slip"],
            ["ベビードール", "babydoll"],
            ["テディ", "teddy"],
            ["コルセット", "corset"],
            ["ビスチェ", "bustier"],
            ["ガーターベルト", "garter belt"]
          ],
          "レッグウェア":[
            ["ストッキング", "stockings"],
            ["タイツ", "tights"],
            ["ハイソックス", "high socks"],
            ["ニーソックス", "knee socks"],
            ["ソックス", "socks"]
          ],
           "部屋着":[
            ["ローブ", "robe"],
            ["パジャマ","pajamas"],
            ["ルームウェア","room wear"]
          ],
           "男性下着":[
            ["ブリーフ", "briefs"],
            ["ボクサーパンツ", "boxer shorts"]
          ],
          "特殊な下着":[
            ["Tバック", "thong"],
            ["Gストリング", "g-string"],
            ["ヒップハンガー", "hipsters"],
            ["ペチコート", "petticoat"],
            ["ブラレット", "bralette"],
            ["ノンワイヤーブラ", "non-wired bra"],
            ["スポーツブラ", "sports bra"],
            ["プランジブラ", "plunge bra"],
            ["ハーフカップブラ", "half cup bra"],
            ["フルカップブラ", "full cup bra"],
            ["タンクトップブラ","tank top bra"],
            ["ワイヤレスブラ","wireless bra"],
            ["オープンブラ", "open bra"],
            ["レースブラ", "lace bra"],
            ["メッシュブラ", "mesh bra"],
            ["シームレスショーツ", "seamless panties"],
            ["レースショーツ", "lace panties"],
            ["ハイウエストショーツ", "high-waist panties"],
            ["ローライズショーツ","low-rise panties"],
            ["コットンショーツ", "cotton panties"],
            ["シルクショーツ","silk panties"],
            ["レザーランジェリー", "leather lingerie"],
            ["サテンランジェリー", "satin lingerie"],
            ["シースルーランジェリー", "see-through lingerie"],
            ["メッシュランジェリー","mesh lingerie"],
            ["リボン付きランジェリー","ribbon lingerie"],
            ["フリル付きランジェリー","frilly lingerie"],
            ["ボディストッキング", "bodystocking"]
          ]
        }
      },
      "アクセサリー": [
        ["なし", "no accessories"],
        ["ネックレス", "necklace"],
        ["チョーカー", "choker"],
        ["ペンダント", "pendant"],
        ["ロケットペンダント", "locket pendant"],
        ["イヤリング", "earrings"],
        ["ピアス", "piercing"],
        ["指輪", "ring"],
        ["ブレスレット", "bracelet"],
        ["バングル", "bangle"],
        ["アンクレット", "anklet"],
        ["ヘアピン", "hairpin"],
        ["バレッタ", "barrette"],
        ["カチューシャ", "headband"],
        ["ヘアクリップ", "hair clip"],
        ["帽子", "hat"],
        ["キャップ", "cap"],
        ["ベレー帽", "beret"],
        ["ヘッドドレス", "headdress"],
        ["ティアラ", "tiara"],
        ["クラウン", "crown"],
        ["サングラス", "sunglasses"],
        ["メガネ", "glasses"],
        ["伊達メガネ", "fashion glasses"],
        ["腕時計", "watch"],
        ["懐中時計", "pocket watch"],
        ["スカーフ", "scarf"],
        ["ストール", "stole"],
        ["マフラー", "muffler"],
        ["ベルト", "belt"],
        ["ガーターベルト", "garter belt"],
        ["ボディチェーン", "body chain"],
        ["アームレット", "armlet"],
        ["グローブ", "gloves"],
        ["レースの手袋", "lace gloves"],
        ["網タイツ", "fishnet stockings"],
        ["タイツ", "tights"],
        ["レッグウォーマー", "leg warmers"],
        ["ショルダーバッグ", "shoulder bag"],
        ["ハンドバッグ", "handbag"],
        ["リュックサック", "backpack"],
        ["ブローチ", "brooch"],
        ["コサージュ", "corsage"],
        ["扇子", "folding fan"],
        ["傘", "umbrella"],
        ["杖", "cane"]
      ]
    }
  };
